# Base configs
baseurl: "https://photography.konstantis.eu"
image_fulls_loc: "/images/fulls"
image_thumbs_loc: "/images/thumbs"
google_analytics: ""

# UI configs
title: "Photography by Konstantinos Michopoulos"
author: "Konstantinos Michopoulos"

header:
  title: "Photography"
  subtitle: "by Konstantinos Michopoulos"

footer:
  name: "Konstantinos Michopoulos Photography"
  bio: ""
  github: ""

web_design: ""

social_urls:
  instagram: "https://www.instagram.com/michopoulos_/"